# Generated by Django 4.2.6 on 2023-11-06 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_friend_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 20, 49, 5, 575843)),
            preserve_default=False,
        ),
    ]
