# Generated by Django 4.2.6 on 2023-11-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_friend_last_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='last_message',
            new_name='last_message_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
