# Generated by Django 4.2.6 on 2023-11-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_last_message_friend_last_message_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='last_message_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
