# Generated by Django 4.2.6 on 2023-12-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20231203_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='vol/web/media'),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='profile_image',
            field=models.FileField(blank=True, default='/vol/web/media/default.png', null=True, upload_to='vol/web/media'),
        ),
    ]
