# Generated by Django 4.2.6 on 2023-12-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_media_media_alter_profileinfo_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='profile_image',
            field=models.FileField(blank=True, default='static/media/default.png', null=True, upload_to=''),
        ),
    ]
